spring:
  datasource:
    url: jdbc:postgresql://database:5432/offertlyapi
  jpa:
    show-sql: false
    properties:
      hibernate:
        schema_update:
          unique_constraint_strategy: RECREATE_QUIETLY
        hbm2ddl:
          auto: update