spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/offertlyapi
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        hbm2ddl:
          auto: create